name: 自动部署 # 步骤名称

on:
  push:
    branches:
      - main # 当 main 分支发生提交时触发
    # paths-ignore: # 避免这些文件改变时触发
    #   - README.md
    #   - LICENSE
    paths: # 指定哪些文件改变时触发
      - src/**
      - package.json

jobs:
  deploy:
    runs-on: ubuntu-latest # 指定用什么版本服务器来执行

    steps:
      - name: SSH 命令拉取代码
        uses: appleboy/ssh-action@master
        with:
          # 这里配置对应仓库设置的变量，就可以避免服务器配置暴露
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd /home/ec2-user/web/vue3-project
            git pull
            npm i
            npm run build